name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USSER -p $DOCKER_PASSWORD --password-stdin
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/racecalendar.api:latest .
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/racecalendar.api:latest
