name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Replace DB credentials
      uses: jacobtomlinson/gha-find-replace@v2      
      with:
        find: "<DB_PASSWORD>"
        replace: ${{secrets.DB_PASSWORD}}
    - name: Replace JwtConfig
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "<JWT_SECRET>"
        replace: ${{secrets.JWT_SECRET}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/racecalendar.api:latest .
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/racecalendar.api:latest
