name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Replace DB password
      run: git grep -l '<DB_PASSWORD>' | xargs sed -i 's/<DB_PASSWORD>/${{secrets.DB_PASSWORD}}/g'
      shell: bash
    - name: Replace jwt secret
      run: git grep -l '<JWT_SECRET>' | xargs sed -i 's/<JWT_SECRET>/${{secrets.JWT_SECRET}}/g'
      shell: bash
    - name: Replace discord changes webhook
      run: git grep -l '<DISCORD_CHANGES_WEBHOOK>' | xargs sed -i 's#<DISCORD_CHANGES_WEBHOOK>#${{secrets.DISCORD_CHANGES_WEBHOOK}}#g'
      shell: bash
    - name: Replace discord additions webhook
      run: git grep -l '<DISCORD_ADDITIONS_WEBHOOK>' | xargs sed -i 's#<DISCORD_ADDITIONS_WEBHOOK>#${{secrets.DISCORD_ADDITIONS_WEBHOOK}}#g'
      shell: bash
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USER}}/racecalendar.api:latest .
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/racecalendar.api:latest
